### ISSUE TITLE
The issue while using script

### ISSUE THREAD

**Issue by itsxrp** [R0rt1z2/realme-ota#15]
Kindly help

python main.py RMX3361 RMX3361_11.A.01_001_202202101618 3 -r 1
Traceback (most recent call last):
  File "C:\Users\mnaum\Downloads\realme-ota-master\realme-ota-master\realme_ota\main.py", line 3, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'

**Comment by R0rt1z2** [comment]
> Kindly help
> 
> python main.py RMX3361 RMX3361_11.A.01_001_202202101618 3 -r 1 Traceback (most recent call last): File "C:\Users\mnaum\Downloads\realme-ota-master\realme-ota-master\realme_ota\main.py", line 3, in import requests ModuleNotFoundError: No module named 'requests'

Install the "requests" pip package with `pip3 install requests`.
[I updated](b970d4dceefe489c87db3cdd5f24ecc0c4870c4f) the README to also include requests in the install process.

**Comment by R0rt1z2** [comment]
Closing due to inactivity.
